name: @name@
version: @version@
main: net.toshimichi.dungeons.DungeonsPlugin
api-version: @api@

commands:
  dungeons:
    usage: /dungeons [args]
    description: "Dungeonsの管理用コマンド"
    permission: net.toshimichi.dungeons.help
